server:
  port: 9009
spring:
  application:
    name: tensquare_sms
  rabbitmq:
    host: 192.168.188.133

aliyun:
  sms:
    accessKeyId: 不告诉你
    accessKeySecret: 不告诉你
    template_code: SMS_85735065
    sign_name: 黑马