spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zhymgc/tensquare_dev.git
  rabbitmq:
    host: localhost
server:
  port: 12000
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
